name: Deploy Angular Develop to GitHub Pages (dev site)

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular dev
        run: npm run build -- --configuration development --base-href /poke-tracker/

      - name: Deploy to GitHub Pages (dev)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/poke-tracker/browser
          publish_branch: gh-pages-dev
